vulsdoc/vuls

- docs/usage-report.md
Documentation for https://github.com/future-architect/vuls/pull/597
> Add documentation for the -aws-s3-server-side-encryption option

- docs/usage-report.md
- docs/usage-settings.md
https://github.com/future-architect/vuls/pull/604
> Add Syslog section

- docs/usage-report.md
- docs/usage-settings.md
> Update usage report.md chatwork

- docs/tutorial-docker.md
Docker Host is Debian & Ubuntu Local TimeZone
> Step4. Scan If Docker Host is Debian or Ubuntu

- docs/usage-settings.md
Filled in some missing details after I set a bad settings
stole the info straight from the [code](https://github.com/future-architect/vuls/blob/7585f9d537b70b7cdd2b72ebaf0d239dce71079b/config/config.go#L338)
> adding description for the types of database supported

- docs/usage-report.md
- docs/usage-settings.md
https://github.com/future-architect/vuls/pull/762
> add telegram usage

- docs/architecture-remote-local.md
- docs/main-features.md
- docs/usage-scan-wordpress.md
- docs/usage-scan.md
- website/sidebars.json
https://github.com/future-architect/vuls/pull/769
> add WordPress Scan

- docs/usage-server.md
Resolve the conflict #51 
Thank you
> Fix typo in usage-server.md

- docs/usage-scan-wordpress.md
> add WordPress Tips

- docs/usage-server.md
Updated the document for this change. 
- https://github.com/future-architect/vuls/pull/850
- https://github.com/future-architect/vuls/pull/824
> Updated the server mode document.

- docs/usage-configtest.md
https://github.com/future-architect/vuls/pull/855
> udpate yum-ushida

- docs/abstract.md
Resolves some typos and grammatical issues in the opening of the abstract.
> Clean up abstract language

- docs/install-manually.md
fixed go version from 1.12 to 1.13
> fix go version

- docs/supported-os.md
> fix: add debian10 to supported OS

- docs/install-manually.md
More linear narrative for those less technical of us.
> Expanded text

- docs/supported-os.md
Add that Ubuntu20 support is now available.
> Add supported ubuntu20

- docs/related-projects.md
Changed Releted to Related
Also added my own related project
> Fixed sidebar typo + New related project

- docs/usage-report.md
Replaced contianer by container
> Fixed typo

- docs/usage-server.md
Added missing RedHat/CentOS 7 version
Patched the Ubuntu version
Changed [Your Vuls Server] to `[Your Vuls Server]`
> One-liners patch and visual changes

- docs/usage-report.md
Added few examples to generate all client scan reports or a specific date
> Added examples to generate client scan reports

- docs/usage-server.md
The format for redhat-release in 7.8 ins't working
> The /etc/redhat-release fields aren't working

- docs/tips.md
- docs/usage-configtest.md
- docs/usage-scan.md
- docs/usage-settings.md
See. https://github.com/future-architect/vuls/pull/1005
> add content about sshConfigPath

- docs/usage-configtest.md
- docs/usage-scan.md
https://superuser.com/questions/636283/how-to-allow-user-to-preserve-environment-with-sudo
> add SETENV to sudoers

- docs/usage-settings.md
Add line setting ProxyJump and explain ProxyJump
> Update setting server section

- docs/tutorial-docker.md
Fix the wrong image name
Signed-off-by: Hui Kang <kangh@us.ibm.com>
> Fix image name of Vulsrepo

- docs/go-msfdb.md
- docs/install-manually.md
- docs/install-with-docker.md
- docs/main-features.md
- docs/misc-update-vuls.md
- docs/tutorial-docker.md
- docs/tutorial-local-scan.md
- docs/usage-automatic-discovery.md
- docs/usage-report.md
- docs/usage-server.md
- docs/usage-settings.md
- docs/usage-tui.md
- website/sidebars.json
ref: https://github.com/future-architect/vuls/pull/1011
> add go-msfdb usage

- docs/vulsrepo.md
Added and corrected the usage of VulsRepo for recent versions.
> Update VulsRepo Usage

- docs/install-with-vulsctl.md
Easy reading and easy navigation for others
> Fix url bug in docs

- docs/architecture-cpe-scan.md
It will keep the styling consistent.
> Minor title case change

- docs/related-projects.md
Added latest documentation / feature changes
> Updated `vuls-scripts` project details

- docs/usage-server.md
> Minor text updates

- docs/tutorial-local-scan.md
Pointing VulsRepo links to the internal documentation and updated the link to the online demo
> Updated VulsRepo links

- docs/main-features.md
- docs/usage-scan-wordpress.md
Please validate it.
- We have a new website! | WPScan Blog
https://blog.wpscan.com/2020/10/09/new-wpscan-website.html
Also, I think need update Vuls source.
https://github.com/future-architect/vuls/search?q=%22wpvulndb.com%22
new API endpoint below.
> Update "WordPress Vulnerability Database" link

- docs/vulsrepo.md
It is the latest VulsRepo URL to update, all others are already fixed.
> Update VulsRepo git repo URL

- docs/usage-server.md
Also improved existing `one-liners` by adding the missing `X-Vuls-Server-Name` header.
> Add support for RHEL and Oracle Linux

- docs/related-projects.md
I've added some new features in the [vuls-scripts](https://github.com/Jiab77/vuls-scripts) and reflected them here.
> Add latest features from the vuls-scripts project

- docs/vulsrepo.md
`How to select the data to be displayed` update.
> Update VulsRepo document for v0.2.7

- docs/usage-settings.md
The HTTP config details are missing, this pull request and the next one will explain how to use it.
@kotakanbe, you might have to translate it in Japanese on your side...
> Add HTTP section

- docs/usage-report.md
https://github.com/future-architect/vuls/pull/1157
> add minus plus diff option

- docs/configtoml.md
- docs/usage-report.md
- docs/usage-scan-non-os-packages.md
reference [future-architect/vuls/#1224](https://github.com/future-architect/vuls/pull/1224)
> Update usage to ignore vulnerabilities dismissed on GitHub

- docs/configtoml.md
- docs/usage-automatic-discovery.md
- docs/usage-scan-port.md
- docs/usage-scan.md
refs. https://github.com/future-architect/vuls/pull/1207
> add port scan docs

- docs/architecture-fast-root-scan.md
- docs/architecture-fast-scan.md
- docs/cron.md
- docs/goval-dictionary.md
- docs/install-manually.md
- docs/main-features.md
- docs/supported-os.md
- docs/tutorial-docker.md
- docs/usage-configtest.md
- docs/usage-report.md
- docs/usage-server.md
refs. https://github.com/future-architect/vuls/pull/1266
> docs(rocky): add Rocky Linux

- docs/configtoml.md
add description about Google Chat configuration
https://github.com/future-architect/vuls/pull/1258
> feat report Google Chat

- docs/architecture-fast-root-scan.md
- docs/architecture-fast-scan.md
- docs/cron.md
- docs/goval-dictionary.md
- docs/install-manually.md
- docs/main-features.md
- docs/supported-os.md
- docs/tutorial-docker.md
- docs/usage-configtest.md
- docs/usage-report.md
- docs/usage-server.md
refs. https://github.com/future-architect/vuls/pull/1261/
> docs(alma): add Alma Linux

- docs/tutorial-docker.md
It was no longer working correctly, so I fixed it.
You may need to edit the "HTTP-Server mode" as well.
> Update docker commands.

- docs/supported-os.md
- docs/tutorial-docker.md
- docs/usage-configtest.md
refs. https://github.com/future-architect/vuls/pull/1298
> docs(debian): support debian bullseye

- docs/install-manually.md
- docs/tutorial-docker.md
refs. https://github.com/kotakanbe/go-cve-dictionary/pull/214
> [WIP] feat(go-cve-dictionary): update command

- docs/go-cve-dictionary.md
- docs/go-msfdb.md
- docs/gost.md
- docs/goval-dictionary.md
- docs/install-manually.md
- docs/install-with-docker.md
- docs/misc-update-vuls.md
- docs/tutorial-docker.md
- docs/tutorial-vulsctl-docker.md
- docs/usage-report.md
- docs/usage-scan-non-os-packages.md
- docs/usage-server.md
Update to the current repository owner.
> chore: update repository owner

- docs/go-kev.md
- docs/install-manually.md
- docs/install-with-docker.md
- docs/install-with-vulsctl-host.md
- docs/install-with-vulsctl.md
- docs/misc-update-vuls.md
- docs/tutorial-docker.md
- docs/tutorial-vulsctl-docker.md
- docs/usage-report.md
add [vulsio/go-kev](https://github.com/vulsio/go-kev).
> add go-kev

- docs/architecture-fast-root-scan.md
- docs/architecture-fast-scan.md
- docs/cron.md
- docs/goval-dictionary.md
- docs/install-manually.md
- docs/main-features.md
- docs/supported-os.md
- docs/tutorial-docker.md
- docs/usage-configtest.md
- docs/usage-report.md
- docs/usage-server.md
ref
https://github.com/vulsio/goval-dictionary/pull/196
https://github.com/future-architect/vuls/pull/1367
> feat(fedora): support fedora

- docs/usage-configtest.md
- docs/usage-scan.md
refs https://github.com/future-architect/vuls/pull/1388
> docs: remove -ask-key-password, -ssh-config option

- docs/how-to-contribute.md
- fix how-to-installation
- replace broken link
> fix how-to-contribute

- docs/configtoml.md
- docs/usage-automatic-discovery.md
refs. https://github.com/future-architect/vuls/pull/1417
> docs: add findlock and lockfiles

- docs/architecture-fast-root-scan.md
- docs/architecture-fast-scan.md
- docs/main-features.md
- docs/supported-os.md
- docs/usage-configtest.md
refs https://github.com/future-architect/vuls/pull/1384
> docs: add suse

- docs/configtoml.md
- docs/usage-automatic-discovery.md
- docs/usage-server.md
refs future-architect/vuls#1270
> docs(server): Add examples for ignorePkgsRegexp

- docs/install-manually.md
- docs/main-features.md
- docs/tutorial-docker.md
- docs/tutorial-vulsctl-docker.md
refs. https://github.com/future-architect/vuls/pull/1428
> docs: update go-exploitdb

- docs/supported-os.md
- docs/tutorial-docker.md
- docs/usage-configtest.md
refs: https://github.com/future-architect/vuls/pull/1431
> feat(ubuntu): add Jammy Jellyfish(22.04)

- docs/supported-os.md
- docs/tutorial-docker.md
- docs/usage-configtest.md
support RHEL 9, CentOS Stream 9, Alma Linux 9
> docs(os): add RHEL 9, CentOS Stream 9, Alma Linux 9

- docs/configtoml.md
- docs/usage-automatic-discovery.md
refs https://github.com/future-architect/vuls/pull/1415
> docs: support CIDR Range

- docs/configtoml.md
- docs/go-cti.md
- docs/install-manually.md
- docs/install-with-docker.md
- docs/install-with-vulsctl-host.md
- docs/misc-update-vuls.md
- docs/tutorial-docker.md
- docs/tutorial-vulsctl-docker.md
- docs/usage-automatic-discovery.md
- docs/usage-report.md
- website/sidebars.json
refs. https://github.com/future-architect/vuls/pull/1442
> docs(cti): support go-cti

- docs/supported-os.md
- docs/usage-configtest.md
refs https://github.com/future-architect/vuls/pull/1495
> docs(rocky): set Rocky Linux 9 EOL

- docs/usage-scan-non-os-packages.md
refs https://github.com/future-architect/vuls/pull/1512
> docs(lockfile): behavior of findLock = true

- docs/community.md
- website/core/Footer.js
refs. https://github.com/future-architect/vuls/pull/1524
> docs: update slack invite URL

- docs/usage-server.md
refs https://github.com/future-architect/vuls/pull/1510
> docs: change Amazon Linux 2 query in one liner scan

- docs/install-manually.md
fixes https://github.com/future-architect/vuls/issues/1573
> docs: fix Go version

- docs/supported-os.md
- docs/usage-configtest.md
refs https://github.com/future-architect/vuls/pull/1647
> docs: add ubuntu 23.04

- docs/architecture-fast-root-scan.md
- docs/architecture-fast-scan.md
- docs/main-features.md
- docs/supported-os.md
- docs/tips.md
- docs/usage-configtest.md
- docs/usage-server.md
refs https://github.com/future-architect/vuls/pull/1712
> docs: add MacOS

- docs/supported-os.md
- docs/usage-configtest.md
refs https://github.com/future-architect/vuls/pull/1750
> docs: add ubuntu 23.10

- docs/tutorial-docker.md
Hello,
Just a link correction.
BR,
Quentin
> docs: fix link

- docs/supported-os.md
- docs/usage-configtest.md
refs https://github.com/future-architect/vuls/pull/1788
> docs: add fedora 39

- docs/tutorial-vulsctl-docker.md
add description of the DB format currently used by vuls for Debian
> docs: reference debian in tutorial

- docs/configtoml.md
- docs/usage-automatic-discovery.md
refs. https://github.com/future-architect/vuls/pull/1220
> docs: add tlsInsecureSkipVerify option

- docs/configtoml.md
- docs/usage-automatic-discovery.md
refs. https://github.com/future-architect/vuls/pull/1888
> docs: add tlsMode option

- docs/usage-server.md
ref. https://github.com/future-architect/vuls/pull/2064
> docs: change KERNEL_VERSION cmd
