vulsdoc/vuls

docs/install-manually.md, docs/usage-scan-non-os-packages.md
Hi,  
- I think that it is better to reflect on install command that the version of go is latest.
- I suggest add process to create symbolic link.   
Because after install vuls according to the document and execute vuls scan, the following warning appears when I run vuls tui.   
```  
WARN [localhost] --ovaldb-path=$HOME/oval.sqlite3 is not found. It's recommended to use OVAL to improve scanning accuracy. For details, see https://github.com/kotakanbe/goval-dictionary#usage
WARN [localhost] --gostdb-path=$HOME/gost.sqlite3 is not found. If the scan target server is Debian, RHEL or CentOS, it's recommended to use gost to improve scanning accuracy. To use gost database, see https://github.com/knqyf263/gost#fetch-redhat
WARN [localhost] --exploitdb-path=$HOME/go-exploitdb.sqlite3 is not …
```
=> Update vuls documents

docs/tutorial-docker.md
Small change to include missing '$' in the command. I had missed this in my last PR
=> Add missing command prompt

docs/tutorial-scan-docker-image.md
I updated `tutorial-scan-docker-image.md` by adding how to scan container images with the digest.
=> Add how to scan container images with the digest

docs/usage-settings.md
If we can't send vuls report via Email(Using Gmail),  indicates a place to check Google account setting.
=> Add Gmail account settings

docs/install-with-vulsctl.md
This was an useful missing part for `vulsctl`.
=> Added instructions to deploy `vuls` on the host

docs/usage-server.md
Vuls needs the environment variable `VULS_HTTP_URL` instead of optional arguments.
=> Fix: server usage

docs/usage-settings.md
=> Fix the broken notation

docs/install-with-vulsctl.md
The project structure has changed and it is not reflected in the documentation. I've added the missing `cd docker` otherwise all displayed scripts won't be found.
I've also tried to run them that way `./docker/update-all.sh` but this caused missing scripts errors.
=> Update documentation to reflect the new project structure

docs/usage-server.md
With this fix in goval-dictionnary (https://github.com/kotakanbe/goval-dictionary/pull/108) I was able to detect vulnerabilities on SLES Servers through Vuls server mode.
I just want to add an example in the documentation to explain which value to set when checking a SLES package. (and also mark it as supported in the doc)
=> Add example api call with a SLES package

docs/main-features.md
This way you can keep users on the documentation and direct them on the project page from the VulsRepo documentation
=> Link to the internal documentation of VulsRepo

docs/vulsrepo.md
The command for clone the repo in the "Step 2. Installation" section is wrong and still using the NOT maintained repo.
=> Fix wrong git repo url for vulsrepo

docs/install-with-vulsctl-host.md
I've simply replaced `fetch-all.sh` by `update-all.sh` because the `fetch-all.sh` symlink does not exist in the `install-host` folder.
=> Update script to update databases

docs/usage-report.md
As discussed previously, here are the missing `-to-http` usage instructions.
@kotakanbe, you might have to translate it in Japanese on your side...
=> Add `-to-http` usage instructions

docs/usage-server.md
Fix in usage-server.md to get debian os release from `/etc/debian_version`
=> Fix: vuls server - header option in Debian

docs/install-with-docker.md
Fix typo in [Install with Docker](https://vuls.io/docs/en/install-with-docker.html).
=> docs: fix typo (pulling docker image)

docs/architecture-fast-root-scan.md, docs/architecture-fast-scan.md, docs/cron.md, docs/goval-dictionary.md, docs/install-manually.md, docs/main-features.md, docs/supported-os.md, docs/tutorial-docker.md, docs/usage-configtest.md, docs/usage-report.md, docs/usage-server.md
function to support Fedora is not merged yet.
This reverts commit e84c53ba0087a18d2eca95bc134860099da6fb88, reversing
changes made to 8c6845b75ccd36a7e6a27bc181437519814162fb.
=> Revert "Merge pull request #184 from maito1201/support_fedora"

docs/how-to-contribute.md, docs/usage-report.md
`vuls report` doesn't support Google Cloud Storage option.
Therefore, 
- describ that GCS is not supported and added
- add example of vuls report to put scan result in Google Cloud Storage
=> Add example of vuls report to put scan result in Google Cloud Storage

docs/usage-report.md
`vuls report -to-saas` had deleted 2 years ago.
=> docs(report): delete -to-saas option

docs/go-cve-dictionary.md
> Since we implemented fetching all the years each time, the list command is not so necessary and removed.
> 
> from: https://github.com/vulsio/go-cve-dictionary/pull/214
=> docs: update Usage link, remove list command

docs/install-with-docker.md
* post-install checks aren't consistent
* some of those are printing version and revision
* some of those are printing help (usage)
* option for printing version and revision was changed from `-v` to `version`
* go-cve-dictionary
* goval-dictionary
* gost
I made post-install checks be consistent (to print help).
Because printing version and revision is described in the section "How to confirm version and Git revision".
=> fix: post-install checks aren't consistent

docs/usage-configtest.md
Added /usr/bin/repoquery to /etc/sudoers as a package to be used with AlmaLinux's fast-root scan.
When scanning in AlmaLinux, the following command is being called.
https://github.com/future-architect/vuls/blob/master/scanner/alma.go#L84-L100
But, 'repoquery' is not specified in the document.
https://github.com/vulsdoc/vuls/blob/414e4c15927327dab26526a39aee5601197b667d/docs/usage-configtest.md?plain=1#L107
When we run `vuls scan`, `vuls configtest` in fast-root mode we will be asked to enter a password.
Therefore, I added '/usr/bin/repoquery,' to the document.
=> docs: In fast-root of AlmaLinux, added repoquery to /etc/sudoers

docs/supported-os.md, docs/usage-configtest.md
refs https://github.com/future-architect/vuls/pull/1878
=> docs: add ubuntu 24.04

docs/usage-configtest.md
RHEL fast-root scan need `yum-utils` which contians repoquery and needs-restarting.
=> RHEL fast-root scan need yum-utils

.circleci/config.yml
Fix followiong circleci error.
https://app.circleci.com/pipelines/github/vulsdoc/vuls/415/workflows/eabca164-cfda-4231-b077-b2f5f07046c9/jobs/709
```
Error: LinkageError occurred while loading main class com.crowdin.cli.Cli
java.lang.UnsupportedClassVersionError: com/crowdin/cli/Cli has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0
Exited with code exit status 1
```
=> fix: circleci java version error
